### ISSUE TITLE
"Caused by: java.lang.NoSuchMethodError" while submiting standalone application

### ISSUE THREAD

**Issue by cagdasolgun** [alitouka/spark_dbscan#13]
Hi there,

I'm trying to run an application with spark-submit

`spark-submit \
  --class org.alitouka.spark.dbscan.DbscanDriver \
  --master spark://ip:6066 \
   --executor-memory 200g --driver-memory 200g --conf spark.akka.frameSize=1024 --conf spark.cores.max=16 --conf spark.driver.maxResultSize=10240 \
  --deploy-mode cluster \
  spark_dbscan-assembly-0.0.4.jar \
  --ds-master spark://ip:7077 \
  --ds-jar spark_dbscan-assembly-0.0.4.jar \
  --ds-input hdfs://ip:9000/file.csv \
  --ds-output hdfs://ip:9000/output/ \
  --eps 25 \
  --numPts 30`

as documented [here](https://github.com/alitouka/spark_dbscan/wiki/Using-Spark-DBSCAN-as-a-standalone-application).

But I'm having this error constantly.

> 6/03/16 06:25:52 INFO SparkContext: Created broadcast 8 from broadcast at PointsPartitionedByBoxesRDD.scala:29
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
        at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.rdd.ShuffledRDD.<init>(Lorg/apache/spark/rdd/RDD;Lorg/apache/spark/Partitioner;)V
        at org.alitouka.spark.dbscan.spatial.rdd.PointsPartitionedByBoxesRDD.<init>(PointsPartitionedByBoxesRDD.scala:15)
        at org.alitouka.spark.dbscan.spatial.rdd.PointsPartitionedByBoxesRDD$.apply(PointsPartitionedByBoxesRDD.scala:41)
        at org.alitouka.spark.dbscan.spatial.rdd.PointsPartitionedByBoxesRDD$.apply(PointsPartitionedByBoxesRDD.scala:37)
        at org.alitouka.spark.dbscan.DistributedDbscan.run(DistributedDbscan.scala:41)
        at org.alitouka.spark.dbscan.Dbscan$.train(Dbscan.scala:56)
        at org.alitouka.spark.dbscan.DbscanDriver$.main(DbscanDriver.scala:65)
        at org.alitouka.spark.dbscan.DbscanDriver.main(DbscanDriver.scala)
        ... 6 more

Any idea?

Thanks

**Comment by linux-devil** [comment]
Are you able to resolve this?

**Comment by cagdasolgun** [comment]
@linux-devil unfortunately

**Comment by linux-devil** [comment]
I am still trying to figure out the issue here , I checked my spark version in sbt and its fine .

**Comment by linux-devil** [comment]
Who so ever face this issue , rebuild this project using spark version and use it as a jar

**Comment by helmutneukirchen** [comment]
I also had that problem: it was due to a mismatch of the Spark version assumed in the build.sbt file and actually on my system. After fixing the build.sbt file (replacing "spark-core_2.10" by "spark-core" and "1.1.0" by my version "1.6.1") and doing a re-build, it worked!
