### ISSUE TITLE
spark job running error in spark 1.6.0 after spark-submit

### ISSUE THREAD

**Issue by wanshi87** [alitouka/spark_dbscan#21]
Hi, I met the problems that I cannot run the job, could anyone help me to solve this?
1. I changed the file build.sbt to this: libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.6.0" % "provided".
2. use the Intellij idea to build artifacts to generate the jar file spark_dbscan.jar.
3. submit the job use the following command:
spark-submit   --class org.alitouka.spark.dbscan.DbscanDriver   --master yarn-cluster   hdfs://cdh1:8020/user/spark_dbscan.jar  --ds-jar hdfs://cdh1:8020/user/spark_dbscan.jar --ds-input hdfs://cdh1:8020/user/dbscandata.csv --ds-output hdfs://cdh1:8020/user/output --eps 25 --numPts 30
4. However, the job run failed.
   the info is:
Exception in thread "main" org.apache.spark.SparkException: Application application_1496725696311_0520 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1035)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1082)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Thanks very much!

**Comment by suai723** [comment]
i have same problem~~have you resoulve this problem??

**Comment by suai723** [comment]
i just comment /spatial/DistanceAnalyzer/countClosePointsWithinpartition/  populate   clock & log finally it worked!!!

**Comment by wanshi87** [comment]
@suai723  yes, it is because of the logging function. Annotating related log command would work!!

**Comment by xspring14** [comment]
> @suai723 yes, it is because of the logging function. Annotating related log command would work!!

I don't  occur error here, but my task cost too much time here!
`1. Failed: union at DistanceAnalyzer.scala:89`
So I have to kill this task, did you occur the same problem
