### ISSUE TITLE
Object cannot be cast to Point

### ISSUE THREAD

**Issue by eintopf** [alitouka/spark_dbscan#8]
Hi,

i'm getting the following error when trying to use Spark DBSCAN inside a Java 8 application:
`java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.alitouka.spark.dbscan.spatial.Point;
    at org.alitouka.spark.dbscan.spatial.BoxCalculator.getNumberOfDimensions(BoxCalculator.scala:47)
    at org.alitouka.spark.dbscan.spatial.BoxCalculator.<init>(BoxCalculator.scala:15)
    at org.alitouka.spark.dbscan.spatial.rdd.PointsPartitionedByBoxesRDD$.apply(PointsPartitionedByBoxesRDD.scala:26)
    at org.alitouka.spark.dbscan.DistributedDbscan.run(DistributedDbscan.scala:41)
    at org.alitouka.spark.dbscan.Dbscan$.train(Dbscan.scala:56)
    at org.alitouka.spark.dbscan.Dbscan.train(Dbscan.scala)``

I checked BoxCalculator.getNumberOfDimensions and what it does is taking the first element of the RDD. I don't get the error, because the RDD is of type RDD<Point>, so why does it throw such an error? I also printed rdd.first() one line before Dbscan.train() and it is definitely a "Point". Anyone has an idea?

Thanks!

Best regards,
eintopf

**Comment by eintopf** [comment]
Can be closed... had the dependency set to 0.0.2 (copied from Wiki) - use 0.0.4 for maximal compatibility to Java.
